### ISSUE TITLE
how to run the code

### ISSUE THREAD

**Issue by 2014gaokao** [ankit1khare/Show_Infer_and_Tell-CIC#1]
I have on idea about how to run your code according to your readme

**Comment by SmallSmallQiu** [comment]
me too

**Comment by 2014gaokao** [comment]
@SmallSmallQiu maybe you can refer to my repository

**Comment by SmallSmallQiu** [comment]
> @SmallSmallQiu也许你可以参考我的仓库
我是想借鉴一下这份代码的模型结构，你的好像没有用到他的结构吧

**Comment by 2014gaokao** [comment]
哦，sorry啊

**Comment by SmallSmallQiu** [comment]
> 哦，对不起啊

你现在也是研二吧？还做图像描述方向吗？

**Comment by 2014gaokao** [comment]
开了这方向题，导师也不管，自己瞎搞

**Comment by SmallSmallQiu** [comment]
> 开了这方向题，导师也不管，自己瞎搞

我也差不多，哈哈，你是学硕吗？

**Comment by 2014gaokao** [comment]
是的啊，现在忙着复习准备秋招了，研究是不可能搞研究的
